export const BRAND_ALIASES: Record<string, string> = {
    // Slovak/Czech accented versions
    "skoda": "Škoda",
    "škoda": "Škoda",
    // Common abbreviations
    "vw": "Volkswagen",
    "volkswagen": "Volkswagen",
    "mb": "Mercedes-Benz",
    "mercedes": "Mercedes-Benz",
    "mercedes-benz": "Mercedes-Benz",
    // Standard brands
    "bmw": "BMW",
    "audi": "Audi",
    "toyota": "Toyota",
    "honda": "Honda",
    "ford": "Ford",
    "opel": "Opel",
    "peugeot": "Peugeot",
    "renault": "Renault",
    "citroen": "Citroën",
    "citroën": "Citroën",
    "fiat": "Fiat",
    "hyundai": "Hyundai",
    "kia": "Kia",
    "mazda": "Mazda",
    "nissan": "Nissan",
    "volvo": "Volvo",
    "seat": "SEAT",
    "alfa": "Alfa Romeo",
    "alfa romeo": "Alfa Romeo",
    "dacia": "Dacia",
    "suzuki": "Suzuki",
    "mitsubishi": "Mitsubishi",
    "subaru": "Subaru",
    "lexus": "Lexus",
    "porsche": "Porsche",
    "jaguar": "Jaguar",
    "land rover": "Land Rover",
    "landrover": "Land Rover",
    "jeep": "Jeep",
    "mini": "MINI",
    "smart": "Smart",
    "tesla": "Tesla",
    "chevrolet": "Chevrolet",
    "dodge": "Dodge",
    "cupra": "Cupra",
};

export const MODEL_ALIASES: Record<string, string> = {
    "octavia": "Octavia",
    "fabia": "Fabia",
    "superb": "Superb",
    "kodiaq": "Kodiaq",
    "karoq": "Karoq",
    "scala": "Scala",
    "kamiq": "Kamiq",
    "enyaq": "Enyaq",
    "golf": "Golf",
    "passat": "Passat",
    "tiguan": "Tiguan",
    "polo": "Polo",
    "touran": "Touran",
    "a3": "A3",
    "a4": "A4",
    "a5": "A5",
    "a6": "A6",
    "q3": "Q3",
    "q5": "Q5",
    "q7": "Q7",
    "focus": "Focus",
    "fiesta": "Fiesta",
    "mondeo": "Mondeo",
    "kuga": "Kuga",
    "corsa": "Corsa",
    "astra": "Astra",
    "insignia": "Insignia",
    "mokka": "Mokka",
    "208": "208",
    "308": "308",
    "3008": "3008",
    "clio": "Clio",
    "megane": "Megane",
    "captur": "Captur",
    "i30": "i30",
    "tucson": "Tucson",
    "sportage": "Sportage",
    "ceed": "Ceed",
    "yaris": "Yaris",
    "corolla": "Corolla",
    "rav4": "RAV4",
};

export const BRANDS = [
    { id: "1", name: "Škoda", slug: "skoda" },
    { id: "2", name: "Volkswagen", slug: "volkswagen" },
    { id: "3", name: "BMW", slug: "bmw" },
    { id: "4", name: "Audi", slug: "audi" },
    { id: "5", name: "Mercedes-Benz", slug: "mercedes-benz" },
    { id: "6", name: "Toyota", slug: "toyota" },
    { id: "7", name: "Ford", slug: "ford" },
    { id: "8", name: "Opel", slug: "opel" },
    { id: "9", name: "Peugeot", slug: "peugeot" },
    { id: "10", name: "Renault", slug: "renault" },
    { id: "11", name: "Hyundai", slug: "hyundai" },
    { id: "12", name: "Kia", slug: "kia" },
];

export const MODELS: Record<string, { id: string; name: string }[]> = {
    "1": [
        { id: "m1", name: "Octavia" },
        { id: "m2", name: "Fabia" },
        { id: "m3", name: "Superb" },
        { id: "m4", name: "Kodiaq" },
        { id: "m5", name: "Karoq" },
        { id: "m6", name: "Scala" },
        { id: "m7", name: "Kamiq" },
        { id: "m8", name: "Enyaq" },
    ],
    "2": [
        { id: "m9", name: "Golf" },
        { id: "m10", name: "Passat" },
        { id: "m11", name: "Tiguan" },
        { id: "m12", name: "Polo" },
        { id: "m13", name: "Touran" },
    ],
    "3": [
        { id: "m14", name: "Rad 3" },
        { id: "m15", name: "Rad 5" },
        { id: "m16", name: "X3" },
        { id: "m17", name: "X5" },
    ],
    "4": [
        { id: "m18", name: "A4" },
        { id: "m19", name: "A6" },
        { id: "m20", name: "Q5" },
        { id: "m21", name: "Q7" },
    ],
};

export const EQUIPMENT_OPTIONS = [
    { groupKey: "safety", items: ["ABS", "ESP", "Airbag vodiča", "Airbag spolujazdca", "Bočné airbagy", "Isofix", "Alarm", "Centrálne zamykanie"] },
    { groupKey: "comfort", items: ["Klimatizácia", "Automatická klimatizácia", "Vyhrievané sedadlá", "Elektrické okná", "Elektrické zrkadlá", "Tempomat", "Parkovacie senzory", "Cúvacia kamera"] },
    { groupKey: "exterior", items: ["LED svetlomety", "Hmlové svetlá", "Strešné okno", "Panoramatická strecha", "Ťažné zariadenie", "Metalíza"] },
    { groupKey: "interior", items: ["Kožený interiér", "Navigácia", "Bluetooth", "USB", "Apple CarPlay", "Android Auto", "Digitálny kokpit"] },
];
