export const BRAND_ALIASES: Record<string, string> = {
  // Slovak/Czech accented versions
  skoda: "Škoda",
  škoda: "Škoda",
  // Common abbreviations
  vw: "Volkswagen",
  volkswagen: "Volkswagen",
  mb: "Mercedes-Benz",
  mercedes: "Mercedes-Benz",
  "mercedes-benz": "Mercedes-Benz",
  // Standard brands
  bmw: "BMW",
  audi: "Audi",
  toyota: "Toyota",
  honda: "Honda",
  ford: "Ford",
  opel: "Opel",
  peugeot: "Peugeot",
  renault: "Renault",
  citroen: "Citroën",
  citroën: "Citroën",
  fiat: "Fiat",
  hyundai: "Hyundai",
  kia: "Kia",
  mazda: "Mazda",
  nissan: "Nissan",
  volvo: "Volvo",
  seat: "SEAT",
  alfa: "Alfa Romeo",
  "alfa romeo": "Alfa Romeo",
  dacia: "Dacia",
  suzuki: "Suzuki",
  mitsubishi: "Mitsubishi",
  subaru: "Subaru",
  lexus: "Lexus",
  porsche: "Porsche",
  jaguar: "Jaguar",
  "land rover": "Land Rover",
  landrover: "Land Rover",
  jeep: "Jeep",
  mini: "MINI",
  smart: "Smart",
  tesla: "Tesla",
  chevrolet: "Chevrolet",
  dodge: "Dodge",
  cupra: "Cupra",
};

export const MODEL_ALIASES: Record<string, string> = {
  octavia: "Octavia",
  fabia: "Fabia",
  superb: "Superb",
  kodiaq: "Kodiaq",
  karoq: "Karoq",
  scala: "Scala",
  kamiq: "Kamiq",
  enyaq: "Enyaq",
  golf: "Golf",
  passat: "Passat",
  tiguan: "Tiguan",
  polo: "Polo",
  touran: "Touran",
  a3: "A3",
  a4: "A4",
  a5: "A5",
  a6: "A6",
  q3: "Q3",
  q5: "Q5",
  q7: "Q7",
  focus: "Focus",
  fiesta: "Fiesta",
  mondeo: "Mondeo",
  kuga: "Kuga",
  corsa: "Corsa",
  astra: "Astra",
  insignia: "Insignia",
  mokka: "Mokka",
  "208": "208",
  "308": "308",
  "3008": "3008",
  clio: "Clio",
  megane: "Megane",
  captur: "Captur",
  i30: "i30",
  tucson: "Tucson",
  sportage: "Sportage",
  ceed: "Ceed",
  yaris: "Yaris",
  corolla: "Corolla",
  rav4: "RAV4",
};
