-- =====================================================
-- Autobazar123 - Retired Duplicate Stripe Payment Flow Migration
-- =====================================================
--
-- This migration previously duplicated the full DDL from:
--   20260206_enhance_stripe_payment_flow.sql
--
-- Hard cutover decision:
-- - Keep 20260206_enhance_stripe_payment_flow.sql as the single canonical migration
-- - Retire this duplicate migration body to a no-op so fresh migration runs
--   do not attempt duplicate CREATE POLICY / constraint operations
--
-- Intentional no-op.
